config/routes.rb
Rails.application.routes.draw do
  resources :talks

  root 'talks#index'

end

app/models/talk.rb
class Talk < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
  end

  # GET /talks/new
  def new
    @talk = Talk.new
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talks/1
  # PATCH/PUT /talks/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render :edit }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to talks_url, notice: 'Talk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talk_params
      params.require(:talk).permit(:title, :description, :speaker, :speaker_twitter, :speaker_email, :speaker_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrbTalks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :speaker %><br>
    <%= f.text_field :speaker %>
  </div>
  <div class="field">
    <%= f.label :speaker_twitter %><br>
    <%= f.text_field :speaker_twitter %>
  </div>
  <div class="field">
    <%= f.label :speaker_email %><br>
    <%= f.text_field :speaker_email %>
  </div>
  <div class="field">
    <%= f.label :speaker_url %><br>
    <%= f.text_field :speaker_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing Talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Talks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Speaker</th>
      <th>Speaker twitter</th>
      <th>Speaker email</th>
      <th>Speaker url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
      <tr>
        <td><%= talk.title %></td>
        <td><%= talk.description %></td>
        <td><%= talk.speaker %></td>
        <td><%= talk.speaker_twitter %></td>
        <td><%= talk.speaker_email %></td>
        <td><%= talk.speaker_url %></td>
        <td><%= link_to 'Show', talk %></td>
        <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
        <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>Submit Talk Proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @talk.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @talk.description %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @talk.speaker %>
</p>

<p>
  <strong>Speaker twitter:</strong>
  <%= @talk.speaker_twitter %>
</p>

<p>
  <strong>Speaker email:</strong>
  <%= @talk.speaker_email %>
</p>

<p>
  <strong>Speaker url:</strong>
  <%= @talk.speaker_url %>
</p>

<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>